services:
  postgres:
    container_name: webhooks-postgres
    image: postgres:17
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: webhooks
